import type { BusinessUnit } from "./types.ts";

export const BUSINESS_UNITS: BusinessUnit[] = [
  {
    id: "intake_triage",
    order: 1,
    name: "Intake & Triage",
    chineseName: "统一入口与分流",
    shortName: "Intake",
    purpose: "Unify, deduplicate, classify and route incoming work.",
    outcome: "A clean request with identity, priority and next owner.",
    input: ["Email, form or webhook", "Client and project hints", "SLA metadata"],
    output: ["task_id", "Deduplicated request", "Priority recommendation", "Route"],
    connectors: ["Gmail", "Forms", "Slack/Teams", "Webhook MCP"],
    accent: "coral",
    qualityScore: 9.5,
  },
  {
    id: "customer_service",
    order: 2,
    name: "Customer Service",
    chineseName: "客服与案例处理",
    shortName: "Service",
    purpose: "Prepare grounded client responses, escalations and follow-up.",
    outcome: "A sourced response draft and SLA-safe follow-up plan.",
    input: ["Ticket or complaint", "Account context", "Current SLA policy"],
    output: ["Case summary", "Response draft", "Escalation", "Follow-up task"],
    connectors: ["HubSpot", "Zendesk", "Gmail", "Calendar MCP"],
    accent: "blue",
    qualityScore: 9.3,
  },
  {
    id: "sales_crm",
    order: 3,
    name: "Sales & CRM",
    chineseName: "销售与客户跟进",
    shortName: "Sales",
    purpose: "Qualify opportunities, prepare account actions and draft CRM updates.",
    outcome: "A prioritized account action with a CRM-safe draft.",
    input: ["Lead or account", "CRM history", "Meeting and email signals"],
    output: ["Account brief", "Next best action", "Email draft", "CRM draft"],
    connectors: ["HubSpot", "Apollo", "Brandfetch", "Gmail"],
    accent: "indigo",
    qualityScore: 9.2,
  },
  {
    id: "operations_scheduling",
    order: 4,
    name: "Operations & Scheduling",
    chineseName: "运营、项目与日程",
    shortName: "Operations",
    purpose: "Allocate people, tasks, dependencies and calendar capacity.",
    outcome: "A feasible allocation showing skill fit and downstream impact.",
    input: ["Project demand", "Staff capacity", "Skills and commitments"],
    output: ["Allocation plan", "Calendar changes", "Dependencies", "Approval packet"],
    connectors: ["Linear", "Asana", "Google Calendar", "HRIS MCP"],
    accent: "green",
    qualityScore: 9.5,
  },
  {
    id: "finance_admin",
    order: 5,
    name: "Finance Admin",
    chineseName: "发票、费用与财务行政",
    shortName: "Finance",
    purpose: "Prepare invoice, cost and approval records without professional accounting judgement.",
    outcome: "A reconciled administrative packet for human review.",
    input: ["Invoice or expense", "Project budget", "Approval policy"],
    output: ["Exception list", "Cost summary", "Approval request", "Ledger draft"],
    connectors: ["Xero/QuickBooks API", "Drive", "Approval MCP"],
    accent: "amber",
    qualityScore: 9.0,
  },
  {
    id: "knowledge_documents",
    order: 6,
    name: "Knowledge & Documents",
    chineseName: "知识与文档",
    shortName: "Knowledge",
    purpose: "Retrieve current internal knowledge and compose sourced documents.",
    outcome: "A permission-safe evidence pack using current versions only.",
    input: ["Entity IDs", "Permission group", "Document intent"],
    output: ["Context Packet", "Citations", "Conflict list", "Document draft"],
    connectors: ["Google Drive", "Notion", "SharePoint", "Docs MCP"],
    accent: "violet",
    qualityScore: 9.5,
  },
  {
    id: "marketing_content",
    order: 7,
    name: "Marketing & Content",
    chineseName: "营销与内容",
    shortName: "Content",
    purpose: "Prepare campaign and communication assets subject to approval.",
    outcome: "A brand-safe content package with evidence and review state.",
    input: ["Campaign goal", "Audience", "Brand standard", "Evidence"],
    output: ["Copy", "Brief", "Slides outline", "Publishing approval"],
    connectors: ["OpenAI", "Canva/Gamma", "Google Slides", "Webflow"],
    accent: "pink",
    qualityScore: 8.8,
  },
  {
    id: "research_insights",
    order: 8,
    name: "Research & Insights",
    chineseName: "研究与洞察",
    shortName: "Research",
    purpose: "Create source-backed company, market and operational research.",
    outcome: "A concise brief with source quality and uncertainty visible.",
    input: ["Research question", "Scope", "Known entities", "Source rules"],
    output: ["Research brief", "Source table", "Contradictions", "Open questions"],
    connectors: ["Web Search", "Apollo", "Brandfetch", "Semrush"],
    accent: "cyan",
    qualityScore: 9.1,
  },
  {
    id: "people_onboarding",
    order: 9,
    name: "People & Onboarding",
    chineseName: "招聘、员工与入职",
    shortName: "People",
    purpose: "Support staffing, skills, onboarding and training operations.",
    outcome: "A role-safe onboarding or staffing plan for approval.",
    input: ["Role or employee", "Skills", "Availability", "Onboarding policy"],
    output: ["Skill match", "Checklist", "Training plan", "Manager task"],
    connectors: ["HRIS", "Calendar", "Drive", "Learning MCP"],
    accent: "teal",
    qualityScore: 9.0,
  },
  {
    id: "purchase_order",
    order: 10,
    name: "Purchase & Order",
    chineseName: "采购、供应商与订单",
    shortName: "Purchase",
    purpose: "Prepare vendor comparisons, contractor requests and purchase approvals.",
    outcome: "A comparable, policy-checked purchase recommendation.",
    input: ["Purchase request", "Vendor quotes", "Budget", "Policy"],
    output: ["Comparison", "Risk flags", "Purchase draft", "Approval request"],
    connectors: ["ERP API", "Airtable", "Gmail", "Approval MCP"],
    accent: "orange",
    qualityScore: 8.9,
  },
];
